INSERT INTO netball_mens_period (
  rebounds,
  turnoverHeld,
  centrePassToGoalPerc,
  penalties,
  deflectionWithNoGain,
  generalPlayTurnovers,
  interceptPassThrown,
  gain,
  points,
  goalMisses,
  blocked,
  deflectionWithGain,
  goalAssists,
  tossUpWin,
  centrePassReceives,
  obstructionPenalties,
  feeds,
  playerId,
  squadId,
  startingPositionCode,
  currentPositionCode,
  goals,
  offsides,
  secondPhaseReceive,
  badPasses,
  period,
  breaks,
  blocks,
  badHands,
  missedGoalTurnover,
  possessionChanges,
  goalAttempts,
  contactPenalties,
  quartersPlayed,
  minutesPlayed,
  feedWithAttempt,
  unforcedTurnovers,
  pickups,
  gainToGoalPerc,
  intercepts,
  matchId,
  periodId
)
VALUES (
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
);
