CREATE TABLE netball_womens_nz_match (
  
  -- Match Statistics
  rebounds INT DEFAULT NULL,
  turnoverHeld INT DEFAULT NULL,
  centrePassToGoalPerc INT DEFAULT NULL,
  penalties INT DEFAULT NULL,
  deflectionWithNoGain INT DEFAULT NULL,
  generalPlayTurnovers INT DEFAULT NULL,
  interceptPassThrown INT DEFAULT NULL,
  gain INT DEFAULT NULL,
  points INT DEFAULT NULL,
  netPoints INT DEFAULT NULL,  
  goalMisses INT DEFAULT NULL,
  blocked INT DEFAULT NULL,
  deflectionWithGain INT DEFAULT NULL,
  deflections INT DEFAULT NULL,  
  defensiveRebounds INT DEFAULT NULL,  
  offensiveRebounds INT DEFAULT NULL,  
  goalAssists INT DEFAULT NULL,
  tossUpWin INT DEFAULT NULL,
  centrePassReceives INT DEFAULT NULL,
  obstructionPenalties INT DEFAULT NULL,
  feeds INT DEFAULT NULL,
  passes INT DEFAULT NULL,  
  playerId INT NOT NULL,
  goals INT DEFAULT NULL,
  offsides INT DEFAULT NULL,
  secondPhaseReceive INT DEFAULT NULL,
  badPasses INT DEFAULT NULL,
  breaks INT DEFAULT NULL,
  blocks INT DEFAULT NULL,
  badHands INT DEFAULT NULL,
  missedGoalTurnover INT DEFAULT NULL,
  turnovers INT DEFAULT NULL,  
  squadId INT NOT NULL,
  deflectionPossessionGain INT DEFAULT NULL,
  possessionChanges INT DEFAULT NULL,
  possessions INT DEFAULT NULL,  
  startingPositionCode VARCHAR(45) NOT NULL,
  goalAttempts INT DEFAULT NULL,
  contactPenalties INT DEFAULT NULL,
  quartersPlayed INT DEFAULT NULL,
  minutesPlayed INT DEFAULT NULL,
  feedWithAttempt INT DEFAULT NULL,
  unforcedTurnovers INT DEFAULT NULL,
  pickups INT DEFAULT NULL,
  currentPositionCode VARCHAR(45) NOT NULL,
  gainToGoalPerc INT DEFAULT NULL,
  intercepts INT DEFAULT NULL,

  -- Player Information
  shortDisplayName VARCHAR(45) NOT NULL,
  firstname VARCHAR(45) NOT NULL,
  surname VARCHAR(45) NOT NULL,
  displayName VARCHAR(45) NOT NULL,
  squadName VARCHAR(45) NOT NULL,
  
  -- Match Information
  homeId INT NOT NULL,
  awayId INT NOT NULL,
  opponent VARCHAR(45) NOT NULL,
  round INT NOT NULL,
  fixtureId INT NOT NULL,  -- Referencing from fixture table
  sportId INT NOT NULL,
  matchId INT NOT NULL,  -- Referencing from fixture table
  
  -- Keys
  PRIMARY KEY (matchId, playerId),
  FOREIGN KEY (fixtureId, matchId) REFERENCES netball_womens_nz_fixture(fixtureId, matchId)  -- Composite foreign key
);
