CREATE TABLE afl_mens_match (
  
  -- Match Information
  sportId INT NOT NULL,
  clearances INT DEFAULT NULL,
  tackles INT DEFAULT NULL,
  goals INT DEFAULT NULL,
  squadId INT NOT NULL,
  displayName VARCHAR(50) DEFAULT NULL,
  playerId INT NOT NULL,
  marksContested INT DEFAULT NULL,
  behinds INT DEFAULT NULL,
  goalAssists INT DEFAULT NULL,
  round INT DEFAULT NULL,
  fixtureId INT NOT NULL,
  firstname VARCHAR(45) DEFAULT NULL,  -- Adjusted to match CSV
  opponent VARCHAR(100) DEFAULT NULL,
  positionName VARCHAR(50) DEFAULT NULL,
  squadName VARCHAR(100) DEFAULT NULL,
  surname VARCHAR(50) DEFAULT NULL,
  marks INT DEFAULT NULL,
  inside50s INT DEFAULT NULL,
  kicksIneffective INT DEFAULT NULL,
  marksUncontested INT DEFAULT NULL,
  hitouts INT DEFAULT NULL,
  possessionsUncontested INT DEFAULT NULL,
  marksInside50 INT DEFAULT NULL,
  penalty50sAgainst INT DEFAULT NULL,
  handballs INT DEFAULT NULL,
  disposalEfficiency INT DEFAULT NULL,
  awayId INT DEFAULT NULL,
  positionId INT DEFAULT NULL,
  jumperNumber INT DEFAULT NULL,
  freesFor INT DEFAULT NULL,
  hitoutsToAdvantage INT DEFAULT NULL,
  kicks INT DEFAULT NULL,
  possessionsContested INT DEFAULT NULL,
  kickEfficiency INT DEFAULT NULL,
  positionCode VARCHAR(50) DEFAULT NULL,
  clangers INT DEFAULT NULL,
  shortDisplayName VARCHAR(50) DEFAULT NULL,
  freesAgainst INT DEFAULT NULL,
  disposals INT DEFAULT NULL,
  blocks INT DEFAULT NULL,
  matchId INT NOT NULL,
  homeId INT NOT NULL,
  kicksEffective INT DEFAULT NULL,

  -- Keys
  PRIMARY KEY (matchId, playerId),
  FOREIGN KEY (fixtureId, matchId) REFERENCES afl_mens_fixture(fixtureId, matchId)  -- Composite foreign key
);
